version: '3.1'

services:
  app:
    container_name: forms_app
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      uvicorn form_app.main:app --host 0.0.0.0 --port 8000 --reload    
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: 'very_secret'
      DB_HOST: 'mongo_db'
    networks:
      - app_network
    depends_on:
      mongo_db:
       condition: service_healthy

  mongo_db:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    networks:
      - app_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s


networks:
  app_network:
    driver: bridge
