version: '3.4'

services:
  test_app:
    container_name: test_forms_app
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "
        echo 'Launching tests...' &&
        pytest -vv
      "
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: 'very_secret'
      DB_HOST: 'test_mongo_db'
      DB_NAME: 'test_db'
    networks:
      - app_network
    depends_on:
      test_mongo_db:
       condition: service_healthy

  test_mongo_db:
    image: mongo
    container_name: test_mongo_db
    restart: always
    ports:
      - 27017:27017
    networks:
      - app_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s


networks:
  app_network:
    driver: bridge
